language: python
  python:
    - "3.7"
  matrix:
    include:
      - dist: xenial
      - sudo: true
  install:
    - "pip install -r requirements.txt"
  script:
  - SECRET_KEY="whatever" python manage.py test